name: Test action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello:
    name: Print hello world
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Hello, world!"