name: Test action

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  registry: git.amarth.cloud
  owner: chris
  image: default
  tag: latest

jobs:
  hello:
    name: Print hello world
    runs-on: default
    steps:
      - name: Pull dependencies
        run: |
          git clone https://${{ env.registry }}/${{ env.owner }}/sneeuwvlok.git .

      - name: Install docker
        run: |
          nix-env -iA nixpkgs.podman nixpkgs.fuse
          mkdir -p ~/.config/containers
          echo '{ "default": [ {"type":"insecureAcceptAnything"} ] }' > ~/.config/containers/policy.json

      - name: Log into registry
        run: |
          podman login --username "${{ forge.actor }}" --password "${{ forge.token }}" ${{ env.registry }}

      - name: Build image
        run: >-
          podman build
          -t ${{ env.registry }}/${{ env.owner }}/${{ env.image }}:${{ env.tag }} 
          -f Dockerfile.default
          modules/nixos/services/development/forgejo
        env:
          DOCKER_BUILDKIT: 1

      - name: Push image
        run: |
          podman push ${{ env.registry }}/${{ env.owner }}/${{ env.image }}:${{ env.tag }}