FROM docker.io/nixos/nix:latest

RUN nix-env -iA nixpkgs.nodejs_24 nixpkgs.podman

RUN echo "experimental-features = nix-command flakes pipe-operators" >> /etc/nix/nix.conf
RUN echo '{ "defult": [ {"type":"insecureAcceptAnything"} ] }' >> /etc/containers/policy.json

CMD ["/bin/bash"]